const crypto = require("crypto");
const TRIVIAL_PARTITION_KEY = "0";
const MAX_PARTITION_KEY_LENGTH = 256;

exports.deterministicPartitionKey = (event) => {
  // return '0' when given no event
  if (!event) return TRIVIAL_PARTITION_KEY;

  let candidate;

  // put partitionKey into candidate, if invalid put hash value generated by the event
  if (event.partitionKey) {
    candidate = event.partitionKey;
  } else {
    const data = JSON.stringify(event);
    candidate = crypto.createHash("sha3-512").update(data).digest("hex");
  }

  // convert candidate into string if not
  if (typeof candidate !== "string") {
    candidate = JSON.stringify(candidate);
  }

  // reset candidate by hash digest when it's length exceeds the maximum length
  if (candidate.length > MAX_PARTITION_KEY_LENGTH) {
    candidate = crypto.createHash("sha3-512").update(candidate).digest("hex");
  }

  return candidate;
};